version: 2
jobs:
  front-test:
    docker:
    - image: circleci/node:10.10.0

    working_directory: ~/repo/front

    steps:
    - checkout:
        path: ~/repo

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-

    - run: npm install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    - run:
        name: test
        command: |
          npm run test:ci
          npx codecov@3.0.2
    - run:
        name: lint
        command: npm run lint

    - run:
        name: build
        command: npm run build

workflows:
  version: 2
  build-workflow:
    jobs:
    - front-test
